# https://docs.astral.sh/uv/guides/integration/github/#syncing-and-running

name: Benchmarks and Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  bench:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.4.x"
          enable-cache: true
      - name: Install Mage
        uses: magefile/mage-action@v3
        with:
          install-only: true
          version: v1.15.0

      - name: Set up Python
        run: uv python install
      - name: uv sync
        run: uv sync --all-extras --dev
      - name: run the fuse server (in the background)
        env:
          TAG: latest
        run: |
          make pull-fuse
          make run-fuse
          sleep 2
      - name: run benchmarks
        run: make run-bench
