# https://docs.astral.sh/uv/guides/integration/github/#syncing-and-running

name: Python benchmarks and tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.4.x"
          enable-cache: true
      - name: Set up Python
        run: uv python install
      - name: uv sync
        run: uv sync --all-extras --dev
      - name: run the fuse server (in the background)
        env:
          TAG: latest
        run: |
          make pull-fuse
          make run-fuse
          sleep 2
      - name: run benchmarks
        run: make run-bench
