# https://docs.astral.sh/uv/guides/integration/github/#syncing-and-running

name: Python Quality Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.4.x"
          enable-cache: true
      - name: Set up Python
        run: uv python install
      - name: uv sync
        run: uv sync --all-extras --dev

      - name: install pyright
        run: uv run pip install pyright
      - name: pyright
        run: make typecheck
      - name: pytest
        run: make test
      - uses: astral-sh/ruff-action@v1
        with:
          args: "format --check"
